### html table parser

In [33]:
from html_table_parser import parser_functions as parser
#pip install html_tabe_parser

In [42]:
code = '005930'
url = 'https://finance.naver.com/item/sise_day.nhn?code='+code

src = urlopen(url).read()

In [43]:
soup = BeautifulSoup(src,'html.parser')

In [44]:
text = soup.select_one('table')
text

<table cellspacing="0" class="type2">
<tr>
<th>날짜</th>
<th>종가</th>
<th>전일비</th>
<th>시가</th>
<th>고가</th>
<th>저가</th>
<th>거래량</th>
</tr>
<tr>
<td colspan="7" height="8"></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2020.08.11</span></td>
<td class="num"><span class="tah p11">59,000</span></td>
<td class="num">
<img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"><span class="tah p11 red02">
				1,200
				</span>
</img></td>
<td class="num"><span class="tah p11">58,000</span></td>
<td class="num"><span class="tah p11">59,500</span></td>
<td class="num"><span class="tah p11">57,800</span></td>
<td class="num"><span class="tah p11">18,080,584</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2020.08.10</span></td>
<td class="num"><span class="tah p11">57,800</span></td>
<td class="num">
<img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"><span class="tah p11 red02">
				300
				</span>
</img></td>
<td class="num"><span class="tah p11">57,600</span></td>
<td class="num"><span class="tah p11">58,300</span></td>
<td class="num"><span class="tah p11">57,500</span></td>
<td class="num"><span class="tah p11">17,774,291</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2020.08.07</span></td>
<td class="num"><span class="tah p11">57,500</span></td>
<td class="num">
<img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"><span class="tah p11 nv01">
				500
				</span>
</img></td>
<td class="num"><span class="tah p11">57,900</span></td>
<td class="num"><span class="tah p11">58,400</span></td>
<td class="num"><span class="tah p11">57,100</span></td>
<td class="num"><span class="tah p11">18,751,717</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2020.08.06</span></td>
<td class="num"><span class="tah p11">58,000</span></td>
<td class="num">
<img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"><span class="tah p11 red02">
				1,100
				</span>
</img></td>
<td class="num"><span class="tah p11">57,100</span></td>
<td class="num"><span class="tah p11">58,400</span></td>
<td class="num"><span class="tah p11">57,100</span></td>
<td class="num"><span class="tah p11">21,625,874</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2020.08.05</span></td>
<td class="num"><span class="tah p11">56,900</span></td>
<td class="num">
<img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"><span class="tah p11 nv01">
				400
				</span>
</img></td>
<td class="num"><span class="tah p11">57,300</span></td>
<td class="num"><span class="tah p11">57,500</span></td>
<td class="num"><span class="tah p11">56,300</span></td>
<td class="num"><span class="tah p11">17,739,706</span></td>
</tr>
<tr>
<td colspan="7" height="8"></td>
</tr>
<tr>
<td bgcolor="#e1e1e1" colspan="7" height="1"></td>
</tr>
<tr>
<td colspan="7" height="8"></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2020.08.04</span></td>
<td class="num"><span class="tah p11">57,300</span></td>
<td class="num">
<img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"><span class="tah p11 red02">
				500
				</span>
</img></td>
<td class="num"><span class="tah p11">57,200</span></td>
<td class="num"><span class="tah p11">58,100</span></td>
<td class="num"><span class="tah p11">57,000</span></td>
<td class="num"><span class="tah p11">19,419,694</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2020.08.03</span></td>
<td class="num"><span class="tah p11">56,800</span></td>
<td class="num">
<img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"><span class="tah p11 nv01">
				1,100
				</span>
</img></td>
<td class="num"><span class="tah p11">57,800</span></td>
<td class="num"><span class="tah p11">57,900</span></td>
<td class="num"><span class="tah p11">56,700</span></td>
<td class="num"><span class="tah p11">21,158,940</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2020.07.31</span></td>
<td class="num"><span class="tah p11">57,900</span></td>
<td class="num">
<img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"><span class="tah p11 nv01">
				1,100
				</span>
</img></td>
<td class="num"><span class="tah p11">59,500</span></td>
<td class="num"><span class="tah p11">59,600</span></td>
<td class="num"><span class="tah p11">57,700</span></td>
<td class="num"><span class="tah p11">21,943,345</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2020.07.30</span></td>
<td class="num"><span class="tah p11">59,000</span></td>
<td class="num">
<span class="tah p11">0</span>
</td>
<td class="num"><span class="tah p11">59,700</span></td>
<td class="num"><span class="tah p11">60,100</span></td>
<td class="num"><span class="tah p11">59,000</span></td>
<td class="num"><span class="tah p11">19,285,354</span></td>
</tr>
<tr onmouseout="mouseOut(this)" onmouseover="mouseOver(this)">
<td align="center"><span class="tah p10 gray03">2020.07.29</span></td>
<td class="num"><span class="tah p11">59,000</span></td>
<td class="num">
<img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"><span class="tah p11 red02">
				400
				</span>
</img></td>
<td class="num"><span class="tah p11">60,300</span></td>
<td class="num"><span class="tah p11">60,400</span></td>
<td class="num"><span class="tah p11">58,600</span></td>
<td class="num"><span class="tah p11">36,476,611</span></td>
</tr>
<tr>
<td colspan="7" height="8"></td>
</tr>
</table>

In [45]:
table = parser.make2d(text)
table

[['날짜', '종가', '전일비', '시가', '고가', '저가', '거래량'],
 ['', '', '', '', '', '', ''],
 ['2020.08.11', '59,000', '1,200', '58,000', '59,500', '57,800', '18,080,584'],
 ['2020.08.10', '57,800', '300', '57,600', '58,300', '57,500', '17,774,291'],
 ['2020.08.07', '57,500', '500', '57,900', '58,400', '57,100', '18,751,717'],
 ['2020.08.06', '58,000', '1,100', '57,100', '58,400', '57,100', '21,625,874'],
 ['2020.08.05', '56,900', '400', '57,300', '57,500', '56,300', '17,739,706'],
 ['', '', '', '', '', '', ''],
 ['', '', '', '', '', '', ''],
 ['', '', '', '', '', '', ''],
 ['2020.08.04', '57,300', '500', '57,200', '58,100', '57,000', '19,419,694'],
 ['2020.08.03', '56,800', '1,100', '57,800', '57,900', '56,700', '21,158,940'],
 ['2020.07.31', '57,900', '1,100', '59,500', '59,600', '57,700', '21,943,345'],
 ['2020.07.30', '59,000', '0', '59,700', '60,100', '59,000', '19,285,354'],
 ['2020.07.29', '59,000', '400', '60,300', '60,400', '58,600', '36,476,611'],
 ['', '', '', '', '', '', '']]

In [70]:
df = pd.DataFrame(table)
df = df.drop([1,7,8,9,15])
df = df.reindex()

In [71]:
df

             0       1      2       3       4       5           6
0           날짜      종가    전일비      시가      고가      저가         거래량
2   2020.08.11  59,000  1,200  58,000  59,500  57,800  18,080,584
3   2020.08.10  57,800    300  57,600  58,300  57,500  17,774,291
4   2020.08.07  57,500    500  57,900  58,400  57,100  18,751,717
5   2020.08.06  58,000  1,100  57,100  58,400  57,100  21,625,874
6   2020.08.05  56,900    400  57,300  57,500  56,300  17,739,706
10  2020.08.04  57,300    500  57,200  58,100  57,000  19,419,694
11  2020.08.03  56,800  1,100  57,800  57,900  56,700  21,158,940
12  2020.07.31  57,900  1,100  59,500  59,600  57,700  21,943,345
13  2020.07.30  59,000      0  59,700  60,100  59,000  19,285,354
14  2020.07.29  59,000    400  60,300  60,400  58,600  36,476,611